# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.Repository.LocalPath)/*'
    azureSubscription: 'Visual Studio Premium with MSDN(05d350cc-8f30-461d-be5b-493477eaa418)'
    Destination: 'AzureBlob'
    storage: 'spataforerecipekeeper'
    ContainerName: '$web'

